# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent-chat-engine/v1/agent_chat_engine.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'agent-chat-engine/v1/agent_chat_engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sdk.pb.google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from sdk.pb.microcommon.v1 import common_pb2 as microcommon_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,agent-chat-engine/v1/agent_chat_engine.proto\x12\x14\x61gent_chat_engine.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bmicrocommon/v1/common.proto\"/\n\x0eHistoryMessage\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x02 \x01(\t\"\x88\x01\n\x0b\x43\x61llRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\'\n\x05\x61gent\x18\x02 \x01(\x0b\x32\x18.microcommon.v1.Resource\x12\r\n\x05query\x18\x03 \x01(\t\x12\x35\n\x07history\x18\x04 \x03(\x0b\x32$.agent_chat_engine.v1.HistoryMessage\"k\n\x0c\x43\x61llResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x02 \x01(\t\x12\x0f\n\x07latency\x18\x03 \x01(\x03\x12.\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xa2\x01\n\x11StreamCallRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\'\n\x05\x61gent\x18\x02 \x01(\x0b\x32\x18.microcommon.v1.Resource\x12\r\n\x05query\x18\x03 \x01(\t\x12\x35\n\x07history\x18\x04 \x03(\x0b\x32$.agent_chat_engine.v1.HistoryMessage\x12\x12\n\nshow_debug\x18\x05 \x01(\x08\"q\n\x12StreamCallResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x02 \x01(\t\x12\x0f\n\x07latency\x18\x03 \x01(\x03\x12.\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xca\x01\n\x16\x41gentChatEngineService\x12M\n\x04\x43\x61ll\x12!.agent_chat_engine.v1.CallRequest\x1a\".agent_chat_engine.v1.CallResponse\x12\x61\n\nStreamCall\x12\'.agent_chat_engine.v1.StreamCallRequest\x1a(.agent_chat_engine.v1.StreamCallResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_chat_engine.v1.agent_chat_engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HISTORYMESSAGE']._serialized_start=132
  _globals['_HISTORYMESSAGE']._serialized_end=179
  _globals['_CALLREQUEST']._serialized_start=182
  _globals['_CALLREQUEST']._serialized_end=318
  _globals['_CALLRESPONSE']._serialized_start=320
  _globals['_CALLRESPONSE']._serialized_end=427
  _globals['_STREAMCALLREQUEST']._serialized_start=430
  _globals['_STREAMCALLREQUEST']._serialized_end=592
  _globals['_STREAMCALLRESPONSE']._serialized_start=594
  _globals['_STREAMCALLRESPONSE']._serialized_end=707
  _globals['_AGENTCHATENGINESERVICE']._serialized_start=710
  _globals['_AGENTCHATENGINESERVICE']._serialized_end=912
# @@protoc_insertion_point(module_scope)
